.PHONY: fixtures test bench race
fixtures:  ## write interop fixtures with the reference zarr-python (needs: pip install zarr numcodecs numpy)
	python internal/gen/gen.py
test: ; go test ./...
race: ; go test -race ./...
bench: ; go test -run xxx -bench . -benchmem ./...
